{{- $component := "api" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gr8.fullname" (dict "Release" .Release "component" $component) }}
  labels:
    {{- include "gr8.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
    app: {{ include "gr8.fullname" (dict "Release" .Release "component" $component) }}
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "gr8_signalr_sticky"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: "Lax"
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.api.port }}
      protocol: TCP
  selector:
    {{- include "gr8.selectorLabels" (dict "Release" .Release "component" $component) | nindent 4 }}
