{{- $component := "frontend" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gr8.fullname" (dict "Release" .Release "component" $component) }}
  labels:
    {{- include "gr8.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "gr8.selectorLabels" (dict "Release" .Release "component" $component) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gr8.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: frontend
          image: {{ include "gr8.image" (dict "Values" .Values "component" $component) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
