stages:
  - test
  - secret-detection

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

check-merge-source:
  stage: test
  script:
    - |
      if [ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "main" ] && [ "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" != "develop" ]; then
        echo "ERROR: Only develop can merge into main"
        exit 1
      fi
      echo "Merge source check passed"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

placeholder:
  stage: test
  script:
    - echo "Pipeline OK"
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

frontend-lint:
  stage: test
  image: node:22-alpine
  script:
    - cd frontend/Gr8
    - npm install
    - npm run lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

backend-lint:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - dotnet format backend/Gr8/Gr8.slnx --verify-no-changes
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"